#:schema https://conductor.build/schemas/settings.repo.schema.json

[scripts]
setup = "yarn install --frozen-lockfile"
run = "./node_modules/.bin/next dev --port $CONDUCTOR_PORT"
archive = "rm -rf .next"
run_mode = "concurrent"
